### ISSUE TITLE
Thresholds for 50/100,000 population for newCasesBySpecimenDate, and cases have doubled or more

### ISSUE THREAD

**Issue by mbarton** [guardian/uk-coronavirus-data-alerts#2]
Requires #1 to get the population data

**Comment by amyhughes** [comment]
We've just agreed a 50 cases per 100,000 population threshold. This is because 100 cases per 100,000 is thought to be worrying, and this gives advance warning.

Population numbers are found here: https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates/datasets/populationestimatesforukenglandandwalesscotlandandnorthernireland

They are updated periodically, Pamela thinks the next release is due in August. If we download the file on each run we should ensure we are always using up to date figures. Note: Pamela currently compares what we report to the government dashboard. She will check that the dashboard has also moved to use the latest population figures on the next release.

**Comment by amyhughes** [comment]
Done in #4, #5 and #6
